/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { GoblinConfig } from "../GoblinConfig";

export class GoblinConfig__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GoblinConfig {
    return new Contract(address, _abi, signerOrProvider) as GoblinConfig;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "goblin",
        type: "address",
      },
    ],
    name: "acceptDebt",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "goblin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "debt",
        type: "uint256",
      },
    ],
    name: "killFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "goblin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "debt",
        type: "uint256",
      },
    ],
    name: "workFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
