/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IBaseOracle } from "../IBaseOracle";

export class IBaseOracle__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseOracle {
    return new Contract(address, _abi, signerOrProvider) as IBaseOracle;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getETHPx",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
