/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { InterestModel } from "../InterestModel";

export class InterestModel__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InterestModel {
    return new Contract(address, _abi, signerOrProvider) as InterestModel;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "debt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "floating",
        type: "uint256",
      },
    ],
    name: "getInterestRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
