/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUniswapGoblin } from "../IUniswapGoblin";

export class IUniswapGoblin__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapGoblin {
    return new Contract(address, _abi, signerOrProvider) as IUniswapGoblin;
  }
}

const _abi = [
  {
    inputs: [],
    name: "lpToken",
    outputs: [
      {
        internalType: "contract IUniswapV2Pair",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
