/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { UsingBaseOracle } from "../UsingBaseOracle";

export class UsingBaseOracle__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(_base: string, overrides?: Overrides): Promise<UsingBaseOracle> {
    return super.deploy(_base, overrides || {}) as Promise<UsingBaseOracle>;
  }
  getDeployTransaction(
    _base: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_base, overrides || {});
  }
  attach(address: string): UsingBaseOracle {
    return super.attach(address) as UsingBaseOracle;
  }
  connect(signer: Signer): UsingBaseOracle__factory {
    return super.connect(signer) as UsingBaseOracle__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UsingBaseOracle {
    return new Contract(address, _abi, signerOrProvider) as UsingBaseOracle;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IBaseOracle",
        name: "_base",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "base",
    outputs: [
      {
        internalType: "contract IBaseOracle",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161010d38038061010d8339818101604052602081101561003357600080fd5b5051606081901b6001600160601b0319166080526001600160a01b031660a9610064600039806051525060a96000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635001f3b514602d575b600080fd5b6033604f565b604080516001600160a01b039092168252519081900360200190f35b7f00000000000000000000000000000000000000000000000000000000000000008156fea26469706673582212206320ce64d0b9235ebdbb4d9ea4cc1dced197e960a0f4ccf784eaf69622b8747e64736f6c634300060c0033";
