/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GoblinInterface extends ethers.utils.Interface {
  functions: {
    "health(uint256)": FunctionFragment;
    "liquidate(uint256)": FunctionFragment;
    "reinvest()": FunctionFragment;
    "work(uint256,address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "health",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "reinvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "work",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "health", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reinvest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "work", data: BytesLike): Result;

  events: {};
}

export class Goblin extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GoblinInterface;

  functions: {
    health(id: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    "health(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    liquidate(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "liquidate(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    reinvest(overrides?: Overrides): Promise<ContractTransaction>;

    "reinvest()"(overrides?: Overrides): Promise<ContractTransaction>;

    work(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "work(uint256,address,uint256,bytes)"(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  health(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "health(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  liquidate(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "liquidate(uint256)"(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  reinvest(overrides?: Overrides): Promise<ContractTransaction>;

  "reinvest()"(overrides?: Overrides): Promise<ContractTransaction>;

  work(
    id: BigNumberish,
    user: string,
    debt: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "work(uint256,address,uint256,bytes)"(
    id: BigNumberish,
    user: string,
    debt: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    health(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "health(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidate(id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "liquidate(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    reinvest(overrides?: CallOverrides): Promise<void>;

    "reinvest()"(overrides?: CallOverrides): Promise<void>;

    work(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "work(uint256,address,uint256,bytes)"(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    health(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "health(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidate(id: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "liquidate(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    reinvest(overrides?: Overrides): Promise<BigNumber>;

    "reinvest()"(overrides?: Overrides): Promise<BigNumber>;

    work(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "work(uint256,address,uint256,bytes)"(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    health(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "health(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidate(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "liquidate(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    reinvest(overrides?: Overrides): Promise<PopulatedTransaction>;

    "reinvest()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    work(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "work(uint256,address,uint256,bytes)"(
      id: BigNumberish,
      user: string,
      debt: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
