/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UniswapV2OracleInterface extends ethers.utils.Interface {
  functions: {
    "base()": FunctionFragment;
    "getETHPx(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "base", values?: undefined): string;
  encodeFunctionData(functionFragment: "getETHPx", values: [string]): string;

  decodeFunctionResult(functionFragment: "base", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getETHPx", data: BytesLike): Result;

  events: {};
}

export class UniswapV2Oracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UniswapV2OracleInterface;

  functions: {
    base(overrides?: CallOverrides): Promise<[string]>;

    "base()"(overrides?: CallOverrides): Promise<[string]>;

    getETHPx(pair: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getETHPx(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  base(overrides?: CallOverrides): Promise<string>;

  "base()"(overrides?: CallOverrides): Promise<string>;

  getETHPx(pair: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getETHPx(address)"(
    pair: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    base(overrides?: CallOverrides): Promise<string>;

    "base()"(overrides?: CallOverrides): Promise<string>;

    getETHPx(pair: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getETHPx(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    base(overrides?: CallOverrides): Promise<BigNumber>;

    "base()"(overrides?: CallOverrides): Promise<BigNumber>;

    getETHPx(pair: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getETHPx(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    base(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "base()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getETHPx(
      pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getETHPx(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
